// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: server/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestText   string                 `protobuf:"bytes,1,opt,name=request_text,json=requestText,proto3" json:"request_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_server_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_server_api_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRequestText() string {
	if x != nil {
		return x.RequestText
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseText  string                 `protobuf:"bytes,1,opt,name=response_text,json=responseText,proto3" json:"response_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_server_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_server_api_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResponseText() string {
	if x != nil {
		return x.ResponseText
	}
	return ""
}

var File_server_api_proto protoreflect.FileDescriptor

const file_server_api_proto_rawDesc = "" +
	"\n" +
	"\x10server/api.proto\x12\x03api\",\n" +
	"\aRequest\x12!\n" +
	"\frequest_text\x18\x01 \x01(\tR\vrequestText\"/\n" +
	"\bResponse\x12#\n" +
	"\rresponse_text\x18\x01 \x01(\tR\fresponseText2-\n" +
	"\x04Core\x12%\n" +
	"\x06Handle\x12\f.api.Request\x1a\r.api.ResponseB\aZ\x05./apib\x06proto3"

var (
	file_server_api_proto_rawDescOnce sync.Once
	file_server_api_proto_rawDescData []byte
)

func file_server_api_proto_rawDescGZIP() []byte {
	file_server_api_proto_rawDescOnce.Do(func() {
		file_server_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_proto_rawDesc), len(file_server_api_proto_rawDesc)))
	})
	return file_server_api_proto_rawDescData
}

var file_server_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_api_proto_goTypes = []any{
	(*Request)(nil),  // 0: api.Request
	(*Response)(nil), // 1: api.Response
}
var file_server_api_proto_depIdxs = []int32{
	0, // 0: api.Core.Handle:input_type -> api.Request
	1, // 1: api.Core.Handle:output_type -> api.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_api_proto_init() }
func file_server_api_proto_init() {
	if File_server_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_proto_rawDesc), len(file_server_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_proto_goTypes,
		DependencyIndexes: file_server_api_proto_depIdxs,
		MessageInfos:      file_server_api_proto_msgTypes,
	}.Build()
	File_server_api_proto = out.File
	file_server_api_proto_goTypes = nil
	file_server_api_proto_depIdxs = nil
}
