mixed-port: 7890
external-controller: 127.0.0.1:9090
external-ui: metacubexd
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip

proxy-groups:
  - {name: PROXY, type: select, proxies: [AUTO, DIRECT], include-all: true}
  - {name: AUTO, type: url-test, use: [example], url: http://cp.cloudflare.com/generate_204, interval: 600}

proxy-providers:
  example:
    type: http
    url: http://example.com
    path: ./profiles/example.yaml
    interval: 3600
    health-check: {enable: true, url: http://cp.cloudflare.com/generate_204, interval: 600}

rules:
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
