mixed-port: 7890
external-controller: 127.0.0.1:9090
external-ui: metacubexd
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip

proxy-groups:
  - {name: PROXY, type: select, use: [example]}

proxy-providers:
  example:
    type: http
    url: https://example.com

rules:
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - GEOIP,PRIVATE,DIRECT
  - MATCH,PROXY
