mixed-port: 7890
external-controller: 127.0.0.1:9090
external-ui: metacubexd
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip

geodata-mode: true
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat

proxy-providers:
  provider1:
    type: http
    url: https://example.com
  provider2:
    type: http
    url: https://example.com

proxy-groups:
  - { name: PROXY1, type: select, use: [provider1] }
  - { name: PROXY2, type: select, use: [provider2] }

rules:
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - GEOIP,PRIVATE,DIRECT
  - MATCH,GLOBAL
