void swap(int[], int, int);
void insertion_sort(int[], int);
void shell_sort(int[], int);
void selection_sort(int[], int);
void bubble_sort(int[], int);
void quick_sort(int[], int);
void heap_sort(int[], int);
void merge_sort(int[], int);
void counting_sort(int[], int);
void bucket_sort(int[], int);
void radix_sort(int[], int);
